const Quotes = [
  "Believe you can, and you’re halfway there.",
  "The only way to do great work is to love what you do.",
  "Dream big, work hard, stay focused.",
  "Your vibe attracts your tribe.",
  "Every day may not be good, but there’s something good in every day.",
  "Chase your dreams, not the competition.",
  "In a world where you can be anything, be kind.",
  "The only limit is your mind.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Difficult roads often lead to beautiful destinations.",
  "Radiate positivity like it’s going out of style.",
  "Life is tough, but so are you.",
  "Positivity is a choice; choose wisely.",
  "Embrace the glorious mess that you are.",
  "You are capable of amazing things.",
  "Good vibes only, please.",
  "The sun will rise, and we will try again.",
  "Your energy introduces you before you even speak.",
  "Every day is a second chance.",
  "Let your smile change the world, but don’t let the world change your smile.",
  "Even the darkest night will end, and the sun will rise.",
  "Storms don’t last forever.",
  "When you can’t find the sunshine, be the sunshine.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Stars can’t shine without darkness.",
  "Happiness is not by chance but by choice.",
  "Life is tough, darling, but so are you.",
  "The only way out is through.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "You are capable of amazing things.",
  "Success is not just about what you accomplish, but what you inspire others to do.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t wait for opportunity. Create it.",
  "Success doesn’t come from what you do occasionally; it comes from what you do consistently.",
  "Be stronger than your excuses.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Great things never come from comfort zones.",
  "You didn’t come this far to only come this far.",
  "The only way to predict the future is to create it.",
  "The secret of getting ahead is getting started.",
  "Radiate positivity like it’s going out of style.",
  "Life is tough, but so are you.",
  "Positivity is a choice; choose wisely.",
  "Embrace the glorious mess that you are.",
  "You are capable of amazing things.",
  "Good vibes only, please.",
  "The sun will rise, and we will try again.",
  "Your energy introduces you before you even speak.",
  "Every day is a second chance.",
  "Let your smile change the world, but don’t let the world change your smile.",
];

export default Quotes;
